#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 09 12:46:24 CET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_sprite_rom_behav -key {Behavioral:sim_1:Functional:tb_sprite_rom} -tclbatch tb_sprite_rom.tcl -view /home/bram-laurens/DSO-Opdracht3/tb_vgadriver_behav.wcfg -log simulate.log"
xsim tb_sprite_rom_behav -key {Behavioral:sim_1:Functional:tb_sprite_rom} -tclbatch tb_sprite_rom.tcl -view /home/bram-laurens/DSO-Opdracht3/tb_vgadriver_behav.wcfg -log simulate.log

