# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bram-laurens/SpaceInvaders_V2/SpaceInvaders_V2.srcs/sources_1/ip/uart_bram/uart_bram.xci
# IP: The module: 'uart_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bram-laurens/SpaceInvaders_V2/SpaceInvaders_V2.gen/sources_1/ip/uart_bram/uart_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bram-laurens/SpaceInvaders_V2/SpaceInvaders_V2.srcs/sources_1/ip/uart_bram/uart_bram.xci
# IP: The module: 'uart_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bram-laurens/SpaceInvaders_V2/SpaceInvaders_V2.gen/sources_1/ip/uart_bram/uart_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
